### ISSUE TITLE
git detection bugged

### ISSUE THREAD

**Issue by tenderpork** [xernphoton/git-shell#1]
**Describe the bug**
The method of detecting whether git is installed is not working, or seriously bugged

**To Reproduce**
1. Run the shell script with `./git.sh`

**Expected behavior**
The shell script should recognize that git is installed, and continue on.

**Desktop (please complete the following information):**
WSL 2 Ubuntu 20.04

**Comment by xernphoton** [comment]
can you verify that the output of `command -v git` isn't blank and git is in fact installed on WSL

**Comment by tenderpork** [comment]
![image](https://user-images.githubusercontent.com/14340342/122471787-ab86ab00-cf8d-11eb-9031-66644d7a2699.png)

**Comment by xernphoton** [comment]
does wsl support /dev/null?

**Comment by xernphoton** [comment]
you can simply remove lines 3-7 if it doesn't work for you
